MODULE DMRG
  USE INPUT_VARS
  USE AUX_FUNCS
  USE MATRIX_SPARSE
  USE MATRIX_BLOCKS
  USE TUPLE_BASIS
  USE LIST_OPERATORS
  USE LIST_SECTORS
  USE SITES
  USE BLOCKS
  USE SYSTEM
  USE MEASURE
  implicit none  
END MODULE DMRG
