MODULE DMRG
  USE INPUT_VARS
  USE AUX_FUNCS
  !LIBRARY:
  USE MATRIX_SPARSE
  USE MATRIX_BLOCKS
  USE TUPLE_BASIS
  USE LIST_OPERATORS
  USE LIST_SECTORS
  USE SITES
  USE BLOCKS
  !DMRG
  !USE VARS_GLOBAL!< uncomment this to compile kron_ tests
  USE DMRG_SUPERBLOCK
  USE DMRG_MEASURE
  USE DMRG_SYSTEM
  implicit none  
END MODULE DMRG
