MODULE DMRG
  !GENERAL
  USE INPUT_VARS
  USE AUX_FUNCS
  !AUX MODULES
  USE MATRIX_SPARSE
  USE MATRIX_BLOCKS
  ! USE MATRIX_GRAPH
  USE TUPLE_BASIS
  USE LIST_OPERATORS
  USE LIST_SECTORS
  !DMRG:
  USE SITES
  USE BLOCKS
  USE DMRG_SUPERBLOCK
  USE DMRG_MAIN
  USE DMRG_MEASURE
  !
  !< uncomment this to compile kron_ tests
  USE DMRG_GLOBAL
  USE DMRG_SUPERBLOCK_SETUP
  USE DMRG_CONNECT
  implicit none  
END MODULE DMRG
